name: Deploy spring-boot to Google Cloud
on:
  push:
    branches:
      - 'master'
env:
  GCLOUD_APP_NAME: spring-app
  GCLOUD_PROJECT_ID: editablesite2-37128

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: setup
      uses: google-github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true

    - name: Deploy
      uses: google-github-actions/deploy-appengine@main
      with:
        project_id: ${{ env.GCLOUD_PROJECT_ID }}
        deliverables: ../../app.yaml

