name: Deploy spring-boot to Google Cloud
on:
  push:
    branches:
      - 'master'
env:
  GCLOUD_APP_NAME: spring-app
  GCLOUD_PROJECT_ID: editablesite2-37128

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ env.GCLOUD_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_AACCOUNT_KEY }}

      - name: Deploy to App Engine
        run: gcloud app deploy app.yaml --quiet --no-promote --version v1